// Generated by scripts/optimize-assets.cjs. Content hashes make long caching safe.
window.HwarakAssets = Object.freeze({
  "assets/neon-festival.png": "assets/optimized/neon-festival.464e627651c6.webp",
  "assets/title-logo.png": "assets/optimized/title-logo.49fa4a7f70eb.webp",
  "character/otter-normal.png": "assets/optimized/otter-normal.adc1ba1bc36a.webp",
  "character/skeleton-normal.png": "assets/optimized/skeleton-normal.8c82d5bcc5b7.webp",
  "character/otter-D.png": "assets/optimized/otter-D.5449c76f6950.webp",
  "character/skeleton-D.png": "assets/optimized/skeleton-D.2a413ddaa5f0.webp",
  "character/otter-F.png": "assets/optimized/otter-F.924cf74b2e20.webp",
  "character/skeleton-F.png": "assets/optimized/skeleton-F.780a5e2f5782.webp",
  "character/otter-J.png": "assets/optimized/otter-J.c3bd8c922d7e.webp",
  "character/skeleton-J.png": "assets/optimized/skeleton-J.28e8b1136728.webp",
  "character/otter-K.png": "assets/optimized/otter-K.0b0462cddd38.webp",
  "character/skeleton-K.png": "assets/optimized/skeleton-K.0a974c32b13f.webp",
  "character/otter-DF.png": "assets/optimized/otter-DF.31da1bfeac46.webp",
  "character/skeleton-DF.png": "assets/optimized/skeleton-DF.68c840184f59.webp",
  "character/otter-JK.png": "assets/optimized/otter-JK.85324a135b1a.webp",
  "character/skeleton-JK.png": "assets/optimized/skeleton-JK.bfc1e28cbfdf.webp",
  "character/otter-DJ.png": "assets/optimized/otter-DJ.1adb88633a92.webp",
  "character/skeleton-DJ.png": "assets/optimized/skeleton-DJ.e1b3332a4487.webp",
  "character/otter-FK.png": "assets/optimized/otter-FK.8eaad5881971.webp",
  "character/skeleton-FK.png": "assets/optimized/skeleton-FK.87dc689f2bb8.webp",
  "assets/opening.mp4": "assets/optimized/opening.332aa5a62508.mp4"
});
